
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Review::UnloadingsController, type: :controller do


  # This should return the minimal set of attributes required to create a valid
  # Company. As you add validations to Company, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      vessel_id:  vessel.id,
      port_id:    port.id,
      wpp_id:     wpp.id
    }
  }

  let(:invalid_attributes) {
    {
      vessel_id:  nil,
      port_id:    nil,
      wpp_id:     nil
    }
  }

  let(:admin)     { create :admin }
  let(:unloading1)   { create :unloading }


  let(:vessel)             { create :vessel }
  let(:port)             { create :port }
  let(:wpp)             { create :wpp }

  let(:manta)               { create :manta }
  let(:encountered_manta)   { create :encountered_manta }
  let(:encountered_manta2)  { create :encountered_manta }

  let(:identification1)     { create :identification }
  let(:identification2)     { create :identification }
  let(:identification3)     { create :identification }
  let(:identification4)     { create :identification, status: 'approved' }
  let(:identification5)     { create :identification, status: 'rejected' }



  describe "PUT #update" do
    # we will only test with admin
    # other roles are covered by ability_spec
    before :each do
      admin.roles.push Role.where(name: 'administrator').first_or_create
      sign_in admin
    end
    context "with valid params when approved" do
      let(:new_attributes) {
        { review_state: 'approved' }
      }
      before :each do
        put :update, {:id => unloading1.to_param, :unloading => new_attributes}
      end
      it { expect( assigns(:unloading) ).to eq(unloading1) }
      it { is_expected.to redirect_to unloading_path(unloading1) }
      it { expect( assigns(:unloading).approved? ).to be true }
      it { expect( assigns(:unloading).reviewer ).to eq admin }
      it { expect( assigns(:unloading).reviewed_at.change(:sec => 0) ).to eq Time.now.change(:sec => 0) }
      it { expect( flash[:notice] ).to have_content "Unloading approved!" }
      it {
        is_expected.to permit(:review_state).
          for(:update, params: { id: unloading1, unloading: valid_attributes } ).
          on(:unloading)
        }
    end
    context "with valid params when rejected" do
      let(:new_attributes) {
        { review_state: 'rejected' }
      }
      before :each do
        put :update, {:id => unloading1.to_param, :unloading => new_attributes}
      end
      it { expect( assigns(:unloading) ).to eq(unloading1) }
      it { is_expected.to redirect_to unloading_path(unloading1) }
      it { expect( assigns(:unloading).rejected? ).to be true }
      it { expect( assigns(:unloading).reviewer ).to eq admin }
      it { expect( assigns(:unloading).reviewed_at.change(:sec => 0) ).to eq Time.now.change(:sec => 0) }
      it { expect( flash[:notice] ).to have_content "Unloading rejected!" }
    end
    context "with valid params when pending" do
      let(:new_attributes) {
        { review_state: 'pending' }
      }
      before :each do
        put :update, {:id => unloading1.to_param, :unloading => new_attributes}
      end
      it { expect( assigns(:unloading) ).to eq(unloading1) }
      it { is_expected.to redirect_to unloading_path(unloading1) }
      it { expect( assigns(:unloading).pending? ).to be true }
      it { expect( assigns(:unloading).reviewer).to eq nil }
      it { expect( assigns(:unloading).reviewed_at ).to eq nil }
      it { expect( flash[:notice] ).to have_content "Unloading marked as pending!" }
    end
    context "with invalid params" do
      before :each do
        put :update, {:id => unloading1.to_param, :unloading => invalid_attributes}
      end
      it { expect( assigns(:unloading) ).to eq(unloading1) }
      it { is_expected.to render_template "unloadings/show" }
      it { expect( flash[:error] ).to have_content "There was a problem saving your unloading review." }
    end
  end
end
