development:
  aws:
    aws_access_key_id: AKIAJI3BH4R4JEDW7XCA
    aws_secret_access_key: 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
    directory: Avatar-Riani
  mailer:
    address: cecf547baa89408a3d5d@cloudmailin.net
    server:
    username:
    password:
staging:
  aws:
    aws_access_key_id: AKIAJI3BH4R4JEDW7XCA
    aws_secret_access_key: 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
    directory: Avatar-Riani
  mailer:
    address: cecf547baa89408a3d5d@cloudmailin.net
    server:
    username:
    password:
production:
  aws:
    aws_access_key_id: AKIAJI3BH4R4JEDW7XCA
    aws_secret_access_key: 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
    directory: Avatar-Riani
  mailer:
    address:
    server:
    username:
    password: