
require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Memberships::UsersController, type: :controller do


  # This should return the minimal set of attributes required to create a valid
  # Company. As you add validations to Company, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      email:  'user@example.com'
    }
  }

  let(:invalid_attributes) {
    {
      email:  nil
    }
  }

  let(:admin)     { create :admin }
  let(:company)     { create :company }
  let!(:user)     { create :user }
  let(:user2)     { create :user }


  describe "POST #create" do
    # we will only test with admin
    # other roles are covered by ability_spec
    before :each do
      admin.roles.push Role.where(name: 'administrator').first_or_create
      sign_in admin
    end
    context "with valid and recognized" do
      before :each do
        post :create, { user: { email: user.email } , company_id: company.id}
      end
      it {
        expect {
          post :create, { user: { email: user2.email }, company_id: company.id }
        }.to change(company.users, :count).by(1)
      }
      it { expect(assigns(:object)).to  eq(company) }
      it { expect(assigns(:user)).to    eq(user) }
      it { is_expected.to redirect_to company_path(company) }
      it { expect( flash[:success] ).to have_content "#{user.email} was successfully added to #{company.name}." }
    end
    context "with valid and already member" do
      before :each do
        company.company_positions.create(user_id: user.id, status: 'active')
        post :create, { user: { email: user.email } , company_id: company.id}
      end
      it { expect(assigns(:object)).to  eq(company) }
      it { expect(assigns(:user)).to    eq(user) }
      it { is_expected.to redirect_to company_path(company) }
      it { expect( flash[:notice] ).to have_content "#{user.email} is already a member of #{company.name}." }
    end
    context "with valid and unrecognized" do
      before :each do
        post :create, { user: valid_attributes, company_id: company.id}
      end
      it { expect(assigns(:object)).to eq(company) }
      it { expect(assigns(:user)).to    be_a(User) }
      it { is_expected.to redirect_to company_path(company) }
      it { expect( flash[:alert] ).to have_content "#{valid_attributes[:email]} was successfully invited to #{company.name}." }
    end
    context "with invalid params" do
      before :each do
        post :create, { user: invalid_attributes, company_id: company.id}
      end
      it { expect( assigns(:object) ).to eq(company) }
      it { expect(assigns(:user)).to    be nil }
      it { is_expected.to redirect_to company_path(company) }
      it { expect( flash[:error] ).to have_content "We were unable to add the user to this company." }
    end
  end

  describe "DELETE #destroy"  do
    let(:name)  { company.name }
    # we will only test with superadmin
    # other roles are covered by ability_spec
    before :each do
      company.company_positions.create(user_id: user.id, status: 'active')
      membership = company.company_positions.where(user_id: user.id).last
      company.company_positions.create(user_id: user2.id, status: 'active')
      @membership2 = company.company_positions.where(user_id: user2.id).last
      admin.roles.push Role.where(name: 'administrator').first_or_create
      sign_in admin
      #require 'pry'; binding.pry
      delete :destroy, {:id => membership.to_param, company_id: company.id}
    end
    it { expect {
        delete :destroy, {:id => @membership2.to_param, company_id: company.id}
      }.to change(CompanyPosition, :count).by(-1) }
    it { is_expected.to redirect_to(company_path(company)) }
    it { expect( flash[:notice] ).to have_content "#{user.email} was successfully removed from #{name}." }
  end
end
